version: "1"
rules:
  # hardreset local master with upstream
  - base: master
    upstream: needle-tools:master
    mergeMethod: hardreset
  # create pull request when local master is updated
  - base: openupm
    upstream: master
